# 1. Save as `nginx-nodeport.yaml`
# 2. In bash, `kubectl apply -f nginx-nodeport.yaml`
# 3. If you want to remove, `kubectl delete -f nginx-nodeport.yaml`
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport # Service 的名字
spec:
  type: NodePort
  selector:
    app: nginx # 對應 Pod 的標籤
  ports:
    - protocol: TCP # 可以選擇 TCP 跟 UDP
      port: 80 # 對 service 要 expose 的 port
      targetPort: 80 # 對應 Pod 的 containerPort
      nodePort: 31234 # Worker node 的 Port 31234 會對應到此服務