apiVersion: v1
kind: Service
metadata:
  name: service-a # service name
spec:
  type: ClusterIP
  selector:
    app: other # 對應 Pod 的標籤
  ports:
    - protocol: TCP # or UDP
      port: 80 # 對其他 service expose 的 port
      targetPort: 9376 # 對應 Pod 的 containerPort